openapi: 3.0.1
info:
  title: Chitter Plugin
  description: A plugin that allows users to post and view messages using ChatGPT.
  version: 'v1'
servers:
  - url: https://your-chitter-app-url.com
paths:
  /messages:
    get:
      operationId: getMessages
      summary: Retrieve all messages
      responses:
        "200":
          description: A list of all messages.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessagesResponse'
    post:
      operationId: createMessage
      summary: Post a new message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
      responses:
        "201":
          description: Message created successfully.
components:
  schemas:
    MessagesResponse:
      type: object
      properties:
        messages:
          type: array
          items:
            type: string
          description: An array of messages.
    MessageRequest:
      type: object
      properties:
        message:
          type: string
          description: The message content to post.
